default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost
  port: 3306
  
development:
  <<: *default
  database: message_app
test:
  <<: *default
  database: message_app_test
production:
  <<: *default
  database: message_app_production